import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#131313',
        surface: '#131313',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'surface-bright': '#393939',
        'surface-dim': '#131313',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c6c9ab',
        'on-background': '#e5e2e1',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#909378',
        'outline-variant': '#454932',
        'surface-tint': '#b8d300',
        primary: '#ffffff',
        'primary-container': '#d2f000',
        'on-primary': '#2c3400',
        'on-primary-container': '#5d6b00',
        'primary-fixed': '#d2f000',
        'primary-fixed-dim': '#b8d300',
        'on-primary-fixed': '#191e00',
        'on-primary-fixed-variant': '#414c00',
        'inverse-primary': '#576500',
        secondary: '#ebb2ff',
        'secondary-container': '#b600f8',
        'on-secondary': '#520072',
        'on-secondary-container': '#fff6fc',
        'secondary-fixed': '#f8d8ff',
        'secondary-fixed-dim': '#ebb2ff',
        'on-secondary-fixed': '#320047',
        'on-secondary-fixed-variant': '#74009f',
        tertiary: '#ffffff',
        'tertiary-container': '#ffe16d',
        'on-tertiary': '#3a3000',
        'on-tertiary-container': '#776300',
        'tertiary-fixed': '#ffe16d',
        'tertiary-fixed-dim': '#e9c400',
        'on-tertiary-fixed': '#221b00',
        'on-tertiary-fixed-variant': '#544600',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '16px',
        'margin-mobile': '20px',
        'margin-desktop': '40px',
        'container-max': '1200px',
      },
      fontFamily: {
        'display-lg': ['Sora', 'system-ui', 'sans-serif'],
        'display-lg-mobile': ['Sora', 'system-ui', 'sans-serif'],
        'headline-md': ['Sora', 'system-ui', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
        'display-lg-mobile': [
          '36px',
          { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' },
        ],
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
        'float-up': {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '50%': { opacity: '1' },
          '100%': { transform: 'translateY(-100px)', opacity: '0' },
        },
      },
      animation: {
        'pulse-glow': 'pulse-glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float-up': 'float-up 1.5s ease-out forwards',
      },
      backdropBlur: {
        xs: '4px',
      },
    },
  },
  plugins: [],
};

export default config;
